server:
  port: 8054

spring:
  application:
    name: MachineData-Service
  kafka:
    consumer:
      enable-auto-commit: false

# machine:
#   kafka:
#     consumer:
#       enabled: false
#       concurrency: 1
#       topics: []
#       idempotency:
#         enabled: true
#         key-prefix: "kafka:idempotent:"
#         processing-ttl-seconds: 600
#         done-ttl-hours: 72

